### PR TITLE
Capture usher clade info

### PR DESCRIPTION
**Pull request by theosanderson**

### CODE REVIEW

**Comment by theosanderson** [comment]
@angiehinrichs - you might be interested to use this on your trees -- `usher_to_taxonium [..] --clade_types=nextstrain,pango`. Sorry it took so long to think about displaying this info! The visualisation piece for this is still improving.

**Comment by AngieHinrichs** [comment]
Nice, I'll give that a try!  So far I've been including the Pango assignments from the metadata column pango_lineage_usher, but this will probably be more efficient (and more reflective of what's really in the tree, if there's a problem with the metadata file).

**Comment by theosanderson** [comment]
So these labels can now be viewed by increasing this number from its initial value of 0:
image

In due course I intend to turn them on my default but I need to figure something out. @AngieHinrichs, it would be helpful if you could answer some quick Qs if you have time to see if I understand write about matUtils pruning. I seem to be missing some clade labels on the main Cov2Tree site, like the "BA.2" parental clade label. I now think this because I use TreeShears to prune this tree and that in the process I am losing those nodes. However I am definitely not explicitly pruning e.g. ancestral BA.1 node. Rather I am pruning away a small number of its descendants, and in the process I guess that particular node becomes unnecessary. But I have always assumed that its mutations would get passed onto its descendants, which I think they do? Couldn't its clade annotation be passed on in a similar way, or would that be undesirable?

Sorry if I've got any of that totally wrong :)

**Comment by theosanderson** [comment]
Ah I can now see that you could sometimes get a position where you end up with an ambiguity of whether the collapsed node should get its clade annotation from the parent or the child if it can only have one. Maybe that's (one of) the reasons it's hard.

I'll maybe bring the shears process into the pipeline rather than doing it with UShER and come up with some basic rules for passing on the clades

**Comment by AngieHinrichs** [comment]
Nice!  Yeah, I don't think matUtils currently tries very hard to preserve clade annotations when pruning.  Bringing shears into usher_to_taxonium would definitely give you more control over how that's done.  :)  But if you do, please add an option to not do shears -- I would still like to view the tree as it is in the protobuf.  Thanks!!

**Comment by theosanderson** [comment]
Thanks, super helpful to have that confirmation. And yesh, it definitely won't be on by default

**Pull request merged**
