### PR TITLE
Custom annotation files

### PR DESCRIPTION
**Pull request by amkram**
This is a draft of incorporating custom annotation tracks. It adds the `AddTrackWidget` from the JBrowse data management plugin, which lets users provide annotations in the form of a file or URL.

It's not quite plug-and-play, because (I think?) the plugin might not have been written with the React JBrowse component we are using in mind (`react-linear-genome-view`). Specifically, the plugin tries to call the function `addTrackConf`, but the `state` object does not contain that function. So I manually add that function the state object at line 271 in `JBrowsePanel.jsx`.

Also, to deal with assembly names for custom trees, and different names for the same SARS-CoV-2 assembly, I added a settings modal to the Treenome side to manually set the assembly name.

Most annotation files seem to work, but (some? all?) VCF files cause the window to crash (with an error about "invalid SceneGraph arguments"). I think this is a bug on the JBrowse side, but I'm not positive.

I'll keep trying to trace down what is going on with the VCF files, but I think this could be merged soon-ish if we disallow VCF and if you agree with the changes @theosanderson !

### CODE REVIEW

**Comment by theosanderson** [comment]
Looks really nice. The one change I would suggest if possible is to make sure that added tracks are automatically enabled. Either that (preferable IMO) or keep the Track selector modal up after adding one, so the unselected one is visible. Otherwise it feels as if the addition has done nothing. I realise this may not be trivial given the code is on JBrowse side. (If it looks impossible, so be it). Will leave decision on VCF to you. IMO if like >50% of VCFs fail we should probably disable VCF, if less I don't feel strongly either way. Happy with you merging once you've thought about what you want to do on those two points. Congrats!

**Review by theosanderson — APPROVED** [review]

**Comment by amkram** [comment]
Awesome, thanks. I agree about automatically showing tracks, which should be possible.

Going to spend a little more time looking into the VCF issue -- I think it's potentially solveable. Will update with more details soon

**Comment by amkram** [comment]
So, turns out some of the VCFs I was trying to load were not completely valid. Seems to work fine when the VCF checks out with a validator like (https://github.com/EBIvariation/vcf-validator).

I think it's best not to crash completely if a user uploads an invalid file, so I added an Error Boundary around JBrowse to catch the errors, and display an error "toast".

Here is an example of a valid VCF: https://github.com/amkram/testing/blob/main/500.vcf

And an invalid one: https://github.com/amkram/testing/blob/main/problematic_sites_sarsCov2.vcf

Tracks also show up after being added now.

Look good?

**Comment by theosanderson** [comment]
Hi, this mostly looks good. And the error boundary idea is great and underused in Taxonium atm. But I think when I try a local version of the problematic file it errors silently in a kind of confusing way. (Whereas the URL works). Other than that, good to go. Let me know if you struggle to reproduce

**Comment by amkram** [comment]
Ah - I think this may be because the chromosome names don't match to start out with. For the local version, the assembly/chr name gets set to just "chromosome" until the user changes it with the bottom-right cog. So if you first change the chromosome to "NC_045512v2" then load the problematic_sites file, it should fail correctly (ha).

There might be a better way to indicate that this needs to match the chromosome in uploaded files. Maybe a pop-up dialog when loading the first annotation file?

In the future the chromosome name could maybe be grabbed from the genbank? (unless it already is and I missed that)

**Comment by theosanderson** [comment]
Thanks for explaining! - I was noticing the error below

image

but I guess that's actually to do with trying to show something that doesn't exist. Happy to merge whenever you like. Storing the Chromosome in the metadata sounds good to me. I don't think that's in atm I'm afraid. Feel free to raise an Issue (might take a bit of time to get to I'm afraid) or a PR.

Thanks!

**Comment by amkram** [comment]
Sounds good! Unfortunately that error is coming from deep within the JBrowse plugin as a side effect of using it in a not-so-standard way (I think it tries to add the new track before the state gets updated in react).

I'll go ahead and merge - will also keep looking into ways to avoid those console errors

Thanks

**Comment by theosanderson** [comment]
Awesome

**Pull request merged**
