### PR TITLE
Alternate option for treenome hover

### PR DESCRIPTION
**Pull request by amkram**

### CODE REVIEW

**Comment by amkram** [comment]
I think there is still some weird behavior with this. At a given site sometimes hovering leads to multiple mutations getting highlighted, while other times only the hovered mutation is highlighted (due to the order in which mutations are drawn). @theosanderson  for consistency do you think it would make sense to increase the width of all mutations at a site when hovered?
E.g. this
Screen Shot 2022-08-17 at 3 12 27 PM
rather than this
Screen Shot 2022-08-17 at 3 12 45 PM

**Comment by theosanderson** [comment]
Thanks a lot for thinking about this. I see so (iiuc) the concern for my PR is that mousing over a root mutation in a parent clade pulls the line to the front, even above over-riding mutations in a child clade? Thanks for spotting that.

In code terms the pattern you have here is much nicer, and it's how I initially implemented things for the tree hover. The reason I went to the approach I have now (which is like my PR) is that anything that changes an existing layer with thousands of objects can have fairly big performance implications (and did in the tree case) -- but I haven't looked into them here. I'll have a think and a play around. This may be totally fine :)

**Comment by amkram** [comment]
Thanks! No pressure to go with this way, if the extra layer method works that would be awesome, probably especially for larger genomes with longer mutation lists.

Here's an example of hovering overriding mutations in the child clade. In this case there is a back-mutation to reference, which actually gets drawn as a "mutation" with color equal to the background. So hovering will bring the green mutation line to the front, and the back-mutation doesn't get drawn on top.

https://user-images.githubusercontent.com/6502785/185256928-e75db42e-83a9-4dbf-8fd1-08bc3344f016.mov

**Comment by theosanderson** [comment]
Thanks for that - that actually explains something I hadn't understoood. So in the case of a mutation back to reference we actually paint over the line in the reference colour - as I now see in the code. I'll have a think :)

**Comment by amkram** [comment]
Yeah, sorry, should have mentioned that. It is a slightly hacky thing that decreases the number of unique polygons, which I think helps a lot with performance

**Review by theosanderson — APPROVED** [review]
Sorry for the delay on this. I'm still interested in the ideas in #345 but that has a long way to go. Very happy to get this merged in. :) Thanks

**Comment by amkram** [comment]
Hey @theosanderson  sorry this slipped through the cracks.

I modified this slightly to increase the width of everything at a given site, rather than just the mutation at the vertical mouse position. This avoids the issue I mentioned above that causes different behavior depending on when in the tree the mutation arose.

Let me know if it looks good!

**Pull request closed without merging**
